// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYBu_z2fI894Wq1NugljBTxCZiMaO0oE',
    appId: '1:607926116781:web:15802f10e1d9113b798124',
    messagingSenderId: '607926116781',
    projectId: 'movie-db-936c9',
    authDomain: 'movie-db-936c9.firebaseapp.com',
    storageBucket: 'movie-db-936c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbguNJhjXnp0Yrjhs3lBCsSbSXkL80D7c',
    appId: '1:607926116781:android:40775305a53ed226798124',
    messagingSenderId: '607926116781',
    projectId: 'movie-db-936c9',
    storageBucket: 'movie-db-936c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQWDe1bZbU-WPUz1jI1NI4UIPqBIvu68',
    appId: '1:607926116781:ios:8c181dbb8f5abdc9798124',
    messagingSenderId: '607926116781',
    projectId: 'movie-db-936c9',
    storageBucket: 'movie-db-936c9.appspot.com',
    iosBundleId: 'com.example.themovieproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZQWDe1bZbU-WPUz1jI1NI4UIPqBIvu68',
    appId: '1:607926116781:ios:c05b50b2ee6e0328798124',
    messagingSenderId: '607926116781',
    projectId: 'movie-db-936c9',
    storageBucket: 'movie-db-936c9.appspot.com',
    iosBundleId: 'com.example.themovieproject.RunnerTests',
  );
}
